### PR TITLE
Use Dir instead of git

### PR DESCRIPTION
**Pull request by lussoluca**
I'm using this plugin in a Docker container without GIT so the build fails because the git executable isn't available. We can use Dir instead.

Thanks

### CODE REVIEW

**Comment by mscharley** [comment]
Logstash has a command (`plugin`) to install plugins from the gem repository. You should probably use that instead of this.

**Comment by mscharley** [comment]
```
logstash-plugin install logstash-input-acquia
```

**Comment by mscharley** [comment]
@lussoluca I'd like to close this as unnecessary unless there's some reason you can't use the `plugin` script with Docker.

**Comment by lussoluca** [comment]
@mscharley is the plugin command that doesn't work, see https://gist.github.com/lussoluca/226507a969927964773865e703af9000

`Step 5 : RUN cd /opt/logstash   && bin/plugin install /logstash-input-acquia/logstash-input-acquia-1.6.0.gem
 ---> Running in 2c1ad946be4e
Validating /logstash-input-acquia/logstash-input-acquia-1.6.0.gem
Installing logstash-input-acquia
fatal: Not a git repository (or any of the parent directories): .git`

**Comment by mscharley** [comment]
Weird, it definitely works for us to install. Are you using Logstash 1.x or 2.x? Currently this input only officially supports 1.x since that's we've been using.

For the sake of my curiousity, can you try `bin/plugin install logstash-input-acquia`? That should install it clean from the public gem repositories.

**Comment by mscharley** [comment]
I just played a bit with your Dockerfile and got it working: https://gist.github.com/mscharley/ce385ae9e8f96201767a5e7d8a3c5fdd

**Comment by lussoluca** [comment]
Thanks @mscharley,
with you Dockerfile it works correctly!

**Comment by mscharley** [comment]
There's now an official Docker container with this plugin enabled: https://hub.docker.com/r/equiem/logstash-input-acquia/

**Pull request closed without merging**
